### ISSUE TITLE
Project Schedule + Class Diagram

### ISSUE THREAD

**Issue by fesiib** [fesiib/test_data_generation_with_PDG#1]
Should come up with a Tentative Schedule.

First of all, read all 3 papers related to our project:
1) [Main](https://www.sciencedirect.com/science/article/abs/pii/S095058490500100X)
2) [Feature 1](https://www.sciencedirect.com/science/article/pii/S1877705811017206)
3) [Feature 2](https://reader.elsevier.com/reader/sd/pii/S0950584916300696?token=BE7A36B20D5B8EE8A3767D93990D2263C6E9D1A39AAA24D9E87E3EA1D86611A5632D6307FD3F4531D548E0A857D0B241)

Keep in mind that we have to upload a 10-minute video on Youtube about the project overall till 26 Oct

**Comment by fesiib** [comment]
Objectives:
1) Implement the paper approach for Test Data Generation
2) Apply regeneration of GA (Feature 2)
3) Transform into path-oriented Test Data Generation (Feature 1)

So we shall proceed in the above order.

Below is the tentative class diagram of TDGen
![TDGen_class_diagram](https://user-images.githubusercontent.com/42860511/97410407-5afd0780-1942-11eb-894f-18a40af02838.jpg)

**Comment by fesiib** [comment]
Schedule:

3-4 weeks: Development
1-2 weeks: Experiment & Evaluation
1 week: Wrap-up, Final Presentation

**Comment by Rainhunter13** [comment]
Few questions/suggestions about the class diagram:
1. Shouldn't methods calculate_ease and calculate_improved_ease be for the predicate class and/or calculate_all_eases method for whole coverage table?
2. What do we actually mean by predicate, is it [i == j] or [i==j is true]? I guess the second one as there is a branch field inside predicate class. In that case may be it would be consistent to change method name like get_target_branch -> get_target_predicate desh 
3. I think is_satisfied() for constraint class should be moved to constraints_satisifed(constraint) for test case class, as there is sense of calling constraint.is_satisfied() - for what will satisfaction condition be checked?
4. Does predicate_to_constraint method build a constraint based on the control/data dependence in PDG and targeted predicate? Then may be add PDG class as a field? and create a PDG class actually (although we are not sure about its representation). What is the "mode:int"?

**Comment by Rainhunter13** [comment]
5. We should probably have method "constraint_to_fitness()" for Constraint class and fitness() for TestCase class.

**Comment by fesiib** [comment]
@Rainhunter13 
> 1. Shouldn't methods calculate_ease and calculate_improved_ease be for the predicate class and/or calculate_all_eases method for whole coverage table?

For the `calculate_ease` and `calculate_improved_ease` your approach is pretty much valid it is just a matter of cohesion. But if we do as you suggest, `Predicate` class should be able to access `CoverageTable` and the basic inheritance will be lost. I am not really sure which one will be the best fit here.
I do not think we need something like `calculate_all_eases` because we never take out `ease values` from `CoverageTable`, in most cases all we need is `target_predicate`. But it is okay to include such a function if we need it. Do you want me to integrate it into Class Diagram? @Rainhunter13 

>2. What do we actually mean by predicate, is it [i == j] or [i==j is true]? I guess the second one as there is a branch field inside predicate class. In that case may be it would be consistent to change method name like get_target_branch -> get_target_predicate desh

From Google, a predicate is any function that returns a boolean. The branch is the specific outcome of the predicate, i.e (predicate, true/false). So no.

>3. I think is_satisfied() for constraint class should be moved to constraints_satisifed(constraint) for test case class, as there is sense of calling constraint.is_satisfied() - for what will satisfaction condition be checked?

Greate note, molodes. I guess we need both for modularization's sake.

> 4. Does predicate_to_constraint method build a constraint based on the control/data dependence in PDG and targeted predicate? Then may be add PDG class as a field? and create a PDG class actually (although we are not sure about its representation). What is the "mode:int"?

Yes, if we read the paper you will see that it is exactly that. `mode` in this case is what we take into account while constructing constraint. There are 3 modes AFAIK. 
1. Predicate; 
2. Predicate + Control Dependence;
3. Predicate + Control Dependence + Data Dependence; 
1 < 2 < 3, in a sense of cost (time or memory), so we first try to do GA with only 1 and then 2 and eventually with 3 if some predicates are left.

> 5. We should probably have method "constraint_to_fitness()" for Constraint class and fitness() for TestCase class.

Yeah, I totally forgot about fitness here.

Let's finalize the discussions about the Class Diagram tomorrow. And I will update as necessary. @allbackoff @alishsem any suggestions?

**Comment by Rainhunter13** [comment]
1. Now got it, you approach seems better, leave it as it is then.
2. OK
3. Thanks
4. Now as I am finally red the paper in details, I see the point. That is genius.
5. Sure

**Comment by fesiib** [comment]
This is the final base class diagram, if you have any suggestions, I hope that they are not so fundamental.

I did not add `is_constraints_satisfied`, because we can use `get_fitness` instead of it.

![TDGen_class_diagram_2](https://user-images.githubusercontent.com/42860511/98772054-2f414d80-2429-11eb-8c12-095acdd0df0d.jpg)
