### ISSUE TITLE
Task Distribution

### ISSUE THREAD

**Issue by fesiib** [fesiib/test_data_generation_with_PDG#3]
Looking at the Class Diagram:
1) choose the modules that you want to implement (for now, pass on PDG, Constraint)
2) create a task in todo
3) try to create a new branch (different from master)
4) finally try to create a pull request (let's see how it works)
@fesiib @allbackoff @Rainhunter13 @AlishSem 

![TDG_class_diagram_4](https://user-images.githubusercontent.com/42860511/101617724-5739c600-3a54-11eb-9cdb-d63ff1adfbb8.png)

**Comment by Rainhunter13** [comment]
Few questions before starting coding:

1. Should we create a separate file for each module and just implementing the class?

**Comment by Rainhunter13** [comment]
Okay, I am taking the `Coverage Table` module then.
UPD: and `Predicate` module also as they are too dependent.

UPD1: There should be definitely be a PDG attribute for `calculate_ease` and `calculate_improved_ease` functions. Therefore, I am  assuming for now that PDG would look like a directed graph of predicates - a class with `list[predicates] control_flow` (edges), `list[predicates] data_flow` (other edges) and `int size` attributes at least.
UPD2: But there are two types of edges...(True of False) for each of control/data flows. And may be few things more...
So I think we should define PDG class at this point to continue implementing other functions!
@fesiib @allbackoff @AlishSem

**Comment by allbackoff** [comment]
I'll implement the `Population` module.

**Comment by fesiib** [comment]
> Okay, I am taking the `Coverage Table` module then.
> UPD: and `Predicate` module also as they are too dependent.
> 
> UPD1: There should be definitely be a PDG attribute for `calculate_ease` and `calculate_improved_ease` functions. Therefore, I am assuming for now that PDG would look like a directed graph of predicates - a class with `list[predicates] control_flow` (edges), `list[predicates] data_flow` (other edges) and `int size` attributes at least.
> UPD2: But there are two types of edges...(True of False) for each of control/data flows. And may be few things more...
> So I think we should define PDG class at this point to continue implementing other functions!
> @fesiib @allbackoff @AlishSem

Nice! But could you please create new replies because I am not receiving the notifications?

**Comment by fesiib** [comment]
UPD: Class diagram update
@allbackoff @Rainhunter13 @AlishSem

**Comment by fesiib** [comment]
UPD: Class diagram update

Coverage Table:
1) delete: random_seed();
2) get_target_branch() -> also returns None if there is no target branch that can be chosen;

@allbackoff @Rainhunter13 @AlishSem

**Comment by fesiib** [comment]
UPD: Class Diagram

Population:

1) `initial_population(population_size, test_type)`
test_type = 0 (1 int)
test_type = 1 (2 ints)
test_type = 2 (n ints)

TestCase:

1) New functions
2) string -> int

Constraint

1) `to_fitness(input: List[int])`
2) basically `TestCase.get_fitness(constraint)` will just call `constraint.to_fitness(self.input)`
